const notificationStatus=document.getElementById("notificationStatus");const notificationMessage=document.getElementById("notificationMessage");const enableButton=document.getElementById("enableNotifications");const testButton=document.getElementById("testNotification");const installHint=document.getElementById("installHint");

function updateNotificationUI(){if(!("Notification"in window)){notificationStatus.textContent="Not supported";notificationStatus.className="status-pill status-off";notificationMessage.textContent="This browser does not support web notifications.";enableButton.disabled=true;testButton.disabled=true;return}const p=Notification.permission;if(p==="granted"){notificationStatus.textContent="Enabled";notificationStatus.className="status-pill status-on";notificationMessage.textContent="Notifications are enabled on this device.";enableButton.disabled=true;testButton.disabled=false}else if(p==="denied"){notificationStatus.textContent="Blocked";notificationStatus.className="status-pill status-off";notificationMessage.textContent="Notifications are blocked. Enable them in your browser or device settings.";enableButton.disabled=true;testButton.disabled=true}else{notificationStatus.textContent="Off";notificationStatus.className="status-pill status-off";notificationMessage.textContent="Enable notifications so Birthday Assistant can alert you about upcoming birthdays.";enableButton.disabled=false;testButton.disabled=true}}

async function showLocalTestNotification(title="🎂 Birthday Assistant"){if(!("Notification"in window)||Notification.permission!=="granted")return;const options={body:"Your Birthday Assistant notifications are working!",icon:"./icons/icon-192.png",badge:"./icons/icon-192.png",tag:"birthday-assistant-test",data:{url:"./"}};try{if("serviceWorker"in navigator){const registration=await navigator.serviceWorker.ready;await registration.showNotification(title,options)}else new Notification(title,options)}catch(e){console.error("Could not show notification:",e)}}

async function enableNotifications(){if(!("Notification"in window))return;try{const p=await Notification.requestPermission();if(p==="granted")await showLocalTestNotification("Notifications enabled")}catch(e){console.error("Notification permission error:",e)}updateNotificationUI()}

async function registerServiceWorker(){if(!("serviceWorker"in navigator))return;try{const r=await navigator.serviceWorker.register("./sw.js");console.log("Service worker registered:",r.scope)}catch(e){console.error("Service worker registration failed:",e)}}

enableButton.addEventListener("click",enableNotifications);testButton.addEventListener("click",()=>showLocalTestNotification());

window.addEventListener("load",async()=>{await registerServiceWorker();const standalone=window.matchMedia("(display-mode:standalone)").matches||window.navigator.standalone===true;if(standalone)installHint.textContent="Birthday Assistant is installed as an app. 🎉";else installHint.textContent="On iPhone/iPad, use Share → Add to Home Screen to install the app.";updateNotificationUI()});
