const enablePushBtn=document.getElementById("enablePushBtn"),testLocalBtn=document.getElementById("testLocalBtn"),pushStatus=document.getElementById("pushStatus"),installHint=document.getElementById("installHint");
function setPushStatus(m,ok=false){pushStatus.textContent=m;pushStatus.classList.toggle("success",ok)}
function standalone(){return matchMedia("(display-mode: standalone)").matches||navigator.standalone===true}
function updateHint(){const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream;installHint.textContent=ios&&!standalone()?"📱 On iPhone/iPad, add Birthday Assistant to the Home Screen before enabling remote push notifications.":""}
function OS(){return window.birthdayAssistantOneSignal||null}
async function state(){const o=OS();if(!o)return{optedIn:false,id:null};try{const s=o.User?.PushSubscription;return{optedIn:Boolean(s?.optedIn),id:s?.id||null}}catch(e){console.error(e);return{optedIn:false,id:null}}}
async function refresh(){const o=OS();if(!o){setPushStatus("⚠️ OneSignal could not be initialized. Please refresh the app.");enablePushBtn.disabled=false;return}const s=await state();if(s.optedIn&&s.id){enablePushBtn.textContent="✅ Push Notifications Enabled";enablePushBtn.disabled=true;setPushStatus("Your device is subscribed to OneSignal push notifications.",true);return}enablePushBtn.textContent="🔔 Enable Push Notifications";enablePushBtn.disabled=false;setPushStatus(Notification.permission==="denied"?"⚠️ Notifications are blocked. Enable them in iPhone/iPad Settings.":"Push notifications are not enabled yet.")}
async function enable(){const o=OS();if(!o){setPushStatus("⚠️ OneSignal is not ready. Please wait a few seconds and try again.");return}enablePushBtn.disabled=true;setPushStatus("⏳ Requesting notification permission...");try{if(!(await o.Notifications.requestPermission())){enablePushBtn.disabled=false;setPushStatus("Notifications were not enabled. Please choose Allow when prompted.");return}const s=o.User?.PushSubscription;if(s?.optIn)await s.optIn();for(let i=0;i<15;i++){await new Promise(r=>setTimeout(r,1000));const x=await state();if(x.optedIn&&x.id){enablePushBtn.textContent="✅ Push Notifications Enabled";enablePushBtn.disabled=true;setPushStatus("Your device is subscribed to OneSignal push notifications.",true);return}}enablePushBtn.disabled=false;setPushStatus("⚠️ Permission was allowed, but OneSignal has not confirmed the subscription yet. Close and reopen the installed app, then try again.")}catch(e){console.error(e);enablePushBtn.disabled=false;setPushStatus("⚠️ OneSignal setup failed. Please refresh and try again.")}}
async function localTest(){if(!("Notification"in window)){alert("Notifications are not supported.");return}if(Notification.permission!=="granted"&&await Notification.requestPermission()!=="granted")return;if("serviceWorker"in navigator){const r=await navigator.serviceWorker.ready;await r.showNotification("🎂 Birthday Assistant",{body:"This is a local notification test.",icon:"icons/icon-192.png",badge:"icons/icon-192.png",tag:"birthday-assistant-local-test"})}}
addEventListener("onesignal-ready",refresh);addEventListener("onesignal-error",()=>{setPushStatus("⚠️ OneSignal could not initialize. Please refresh the app.");enablePushBtn.disabled=false});
enablePushBtn.addEventListener("click",enable);testLocalBtn.addEventListener("click",localTest);updateHint();
setTimeout(()=>{if(!OS())setPushStatus("⚠️ OneSignal is taking too long to initialize. Please refresh the app.")},10000);